.\" Manpage for gb.
.\" Contact vincentroy8@gmail.com to correct errors or typos.

.TH gb 1 "14 March 2015" "0.0.2" "gb man page"

.SH NAME
gb \- List git branches with additional information about them.

.SH SYNOPSIS
gb [--merged] [--no-merged] [-a <ahead>] [-b <behind>]

.SH OPTIONS

.IP "-a <ahead>"
only show branches that are <ahead> commits ahead."

.IP "-b <behind>"
only show branches that are <behind> commits behind.

.IP "--merged"
only show branches that are merged.

.IP "--no-merged"
only show branches that are not merged.

.SH BUGS
No known bugs.

.SH SEE ALSO

https://github.com/vroy/gb

.SH AUTHOR
Vincent Roy (vincentroy8@gmail.com)
